// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace GeocodeApp.Api.Models
{
    public partial class Location
    {
        


		[JsonProperty("id")]
        public decimal? Id { get; set; }


		[JsonProperty("address")]
        public object Address { get; set; }


		[JsonProperty("geocodePoints")]
        public object GeocodePoints { get; set; }
    } // end class

} // end Models namespace

