// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace GeocodeApp.Api.Models
{
    public partial class WeatherLatitudeLongitudeGetOKResponseContent
    {
        


		[JsonProperty("id")]
        public decimal? Id { get; set; }


		[JsonProperty("main")]
        public string Main { get; set; }


		[JsonProperty("description")]
        public string Description { get; set; }


		[JsonProperty("dt")]
        public string Dt { get; set; }


		[JsonProperty("current")]
        public object Current { get; set; }


		[JsonProperty("daily")]
        public object Daily { get; set; }
    } // end class

} // end Models namespace

